[project]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "struct_algo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "~=25.1"
